# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant.configure("2") do |config|
#   config.vm.define "server1" do  |server1|
#     server1.vm.box = "ubuntu/bionic64"
#     server1.vm.network "private_network", ip: "10.10.10.11"
#   end
#   config.vm.define "server2" do  |server2|
#     server2.vm.box = "centos/7"
#     server2.vm.network "private_network", ip: "10.10.10.12"
#   end
# end




# Agora vou utizar um provision

Vagrant.configure("2") do |config|
  config.vm.define "server1" do  |server1|
    server1.vm.box = "ubuntu/bionic64"
    server1.vm.network "private_network", ip: "10.10.10.11"
    server1.vm.provision "shell", inline: "sudo apt update && sudo apt install nginx -y"   # Provision para instalar o nginx
  end
end



# Outra forma de fazer o provision utilizando variavel

$script = << EOF
sudo apt-get update
sudo apt-get install apache2 -y
EOF
# String heredoc multilinha , $script é a variável (global em Ruby).



Vagrant.configure("2") do |config|
  config.vm.define "server1" do  |server1|
    server1.vm.box = "ubuntu/bionic64"
    server1.vm.network "private_network", ip: "10.10.10.11"
    server1.vm.provision "shell", inline: $script   # Provision para instalar o apache2
  end
end